@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "com.ood.parkingLot.App#display()",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "com.ood.parkingLot",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "com.ood.parkingLot.App",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_110212 { 
   	label=ood
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1114780195 { 
   	label=parkingLot
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1935947453 { 
   	label=App
	labeljust=l
	fillcolor=white
	style=filled
   
   App1896642096XXXdisplay0[
	label="+ display()"
	style=filled
	fillcolor=white
	tooltip="App

null"
	penwidth=4
	fontcolor=darkgreen
];

App1896642096XXXmain1859653459[
	label="+ main()"
	style=filled
	fillcolor=white
	tooltip="App

null"
	fontcolor=darkgreen
];

App1896642096XXXrun0[
	label="+ run()"
	style=filled
	fillcolor=white
	tooltip="App

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
App1896642096XXXmain1859653459 -> App1896642096XXXdisplay0;
App1896642096XXXmain1859653459 -> App1896642096XXXrun0;
App1896642096XXXrun0 -> App1896642096XXXdisplay0;
    
}
@enduml